# Generated by Django 4.0 on 2022-03-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='isbn',
            new_name='ISBN',
        ),
    ]
